### ISSUE TITLE
Bad URL request

### ISSUE THREAD

**Issue by MickaToast** [codepath/android-oauth-flickr-demo#10]
https://github.com/codepath/android-oauth-flickr-demo/blob/master/app/src/main/java/com/codepath/apps/restclienttemplate/FlickrClient.java#L31

On this line there's "?&" for the URL query parameters, it works fine on non-authentified methods but won't work on a method that need authentification. It provides an error which is: ERROR: auth_problem=signature_invalid

**Solution**: Remplace "?&" by "?".

**Comment by nesquena** [comment]
Fixed, thanks
