### ISSUE TITLE
What is the YOUR API KEY HERE

### ISSUE THREAD

**Issue by freebumba27** [codepath/android-oauth-flickr-demo#4]
in the FlickrClient there is a url with this YOUR API KEY HERE flicker only provide REST_CONSUMER_KEY and REST_CONSUMER_SECRET from where I can get this can you please help me.

**Comment by rogerhu** [comment]
Removed: https://github.com/codepath/android-oauth-flickr-demo/commit/3c6a19ab39a52d37a752fc8d0212cb654c05aa60

There is already a consumer and secret key provided.
